name: CI-CD Pipeline - Automated Pytest Execution

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install selenium pytest
      - name: Run Selenium login test
        run: |
          python login_test.py
      - name: SonarQube Cloud Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=Sireeshanarne_SauceDemo-Selenium-Automation
            -Dsonar.organization=sireeshanarne
